version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
    env_file:
      - ./.env
    command: ["python", "main.py"]