# Generated by Django 5.1.2 on 2024-10-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coldkey', models.CharField(max_length=255)),
                ('hotkey', models.CharField(max_length=255, unique=True)),
                ('stake', models.FloatField()),
                ('parentkey_netuids', models.JSONField(default=list)),
                ('childkeys', models.JSONField(default=list)),
                ('parentkeys', models.JSONField(default=list)),
            ],
        ),
    ]
