# Generated by Django 5.1.2 on 2024-10-16 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotkeyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.FloatField()),
                ('hotkey', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChildHotkeyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netuid', models.IntegerField()),
                ('proportion', models.FloatField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_hotkeys', to='validators.hotkeymodel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_hotkeys', to='validators.hotkeymodel')),
            ],
        ),
    ]
