# Generated by Django 5.1.2 on 2024-10-14 13:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coldkey', models.CharField(max_length=255)),
                ('hotkey', models.CharField(max_length=255, unique=True)),
                ('stake', models.FloatField()),
                ('parentkey_netuids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('childkeys', models.JSONField(blank=True, default=list)),
                ('parentkeys', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='Validator',
        ),
    ]
