# Generated by Django 5.1.2 on 2024-10-16 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childhotkeymodel',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_hotkey', to='validators.hotkeymodel'),
        ),
        migrations.AlterField(
            model_name='childhotkeymodel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_hotkey', to='validators.hotkeymodel'),
        ),
    ]
