# Generated by Django 5.1.2 on 2024-10-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0002_validators_delete_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validators',
            name='parentkey_netuids',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
