# Generated by Django 5.1.2 on 2024-10-14 14:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0003_alter_validators_parentkey_netuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validators',
            name='parentkey_netuids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
