# Generated by Django 5.1.2 on 2024-10-15 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0006_validatorchildkeyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validatorchildkeyinfo',
            name='child_stake',
        ),
        migrations.AlterField(
            model_name='validatorchildkeyinfo',
            name='parent_hotkey',
            field=models.ForeignKey(db_column='parent_hotkey', on_delete=django.db.models.deletion.CASCADE, related_name='child_keys', to='validators.validators', to_field='hotkey'),
        ),
    ]
