# Generated by Django 5.1.2 on 2024-10-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0007_remove_validatorchildkeyinfo_child_stake_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validators',
            old_name='parentkey_netuids',
            new_name='validator_installed_netuids',
        ),
    ]
